### ISSUE TITLE
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to instantiate components

### ISSUE THREAD

**Issue by npatel2012** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#10]
Hello @weimeilin79,

I am unable to set this demo on my local machine.. The init.sh script takes forever - now waiting for more than 40 minutes... Meanwhile I connected via hawtio to find the following 2 containers not coming up properly:

![screenshot from 2015-08-26 13 42 43](https://cloud.githubusercontent.com/assets/1553438/9493597/908cd1ea-4bf8-11e5-98d5-39c7d4c8b890.png)

I then connected to these problematic containers namely "bookingflightcon" and "bookinghotelgcon" to find the following stack trace:

    ERROR: "Unable to start blueprint container for bundle travelagency" 

Stack Trace:

        org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to instantiate components
          at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:680)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:374)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:261)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:270)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:233)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)[org.apache.aries:org.apache.aries.util:1.0.1.redhat-611412]
          at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)[org.apache.aries:org.apache.aries.util:1.0.1.redhat-611412]
          at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)[org.apache.aries:org.apache.aries.util:1.0.1.redhat-611412]
          at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)[org.apache.aries:org.apache.aries.util:1.0.1.redhat-611412]
          at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)[org.apache.aries:org.apache.aries.util:1.0.1.redhat-611412]
          at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1103)[org.apache.felix.framework-4.0.3.redhat-611412.jar:]
          at org.apache.felix.framework.util.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:696)[org.apache.felix.framework-4.0.3.redhat-611412.jar:]
          at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:484)[org.apache.felix.framework-4.0.3.redhat-611412.jar:]
          at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4650)[org.apache.felix.framework-4.0.3.redhat-611412.jar:]
          at org.apache.felix.framework.Felix$4.run(Felix.java:2123)[org.apache.felix.framework-4.0.3.redhat-611412.jar:]
          at org.apache.felix.framework.Felix$5.run(Felix.java:2167)[org.apache.felix.framework-4.0.3.redhat-611412.jar:]
          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_79]
          at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_79]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_79]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_79]
          at java.lang.Thread.run(Thread.java:745)[:1.7.0_79]

        Caused by: java.lang.NoClassDefFoundError: org/apache/openjpa/conf/OpenJPAConfiguration
          at java.lang.Class.getDeclaredMethods0(Native Method)[:1.7.0_79]
          at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)[:1.7.0_79]
          at java.lang.Class.getDeclaredMethods(Class.java:1860)[:1.7.0_79]
          at org.apache.camel.blueprint.handler.CamelNamespaceHandler$CamelInjector.injectMethods(CamelNamespaceHandler.java:738)
          at org.apache.camel.blueprint.handler.CamelNamespaceHandler$CamelInjector.afterInit(CamelNamespaceHandler.java:794)
          at org.apache.aries.blueprint.container.BeanRecipe.runBeanProcPostInit(BeanRecipe.java:744)
          at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:826)
          at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)
          at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)
          at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_79]
          at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.blueprint.di.RefRecipe.internalCreate(RefRecipe.java:62)
          at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:106)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.blueprint.container.BeanRecipe.setProperty(BeanRecipe.java:933)
          at org.apache.aries.blueprint.container.BeanRecipe.setProperties(BeanRecipe.java:907)
          at org.apache.aries.blueprint.container.BeanRecipe.setProperties(BeanRecipe.java:888)
          at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:820)
          at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)
          at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)
          at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_79]
          at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:245)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:183)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
          at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:676)[org.apache.aries.blueprint:org.apache.aries.blueprint.core:1.0.1.redhat-611412]
        ... 20 more

        Caused by: java.lang.ClassNotFoundException: org.apache.openjpa.conf.OpenJPAConfiguration not found by org.apache.servicemix.bundles.spring-orm [133]
          at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)[org.apache.felix.framework-4.0.3.redhat-611412.jar:]
          at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)[org.apache.felix.framework-4.0.3.redhat-611412.jar:]
          at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:358)[:1.7.0_79]
        ... 44 more

Regards,
Niraj

**Comment by eschabell** [comment]
All updated to fuse 6.2, please revisit and reopen if needed.
