### ISSUE TITLE
'org.apache.activemq.camel.component' dependency error

### ISSUE THREAD

**Issue by rafaeltuelho** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#9]
Another provision exception occurs due a dependency on 'org.apache.activemq.camel.component'.

See the full exception on `webendpoint` profile:
```
Provision Exception:
org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requirement [dummy/0.0.0] osgi.identity; osgi.identity=travelagency; type=osgi.bundle; version="[1.0.0,1.0.0]" [caused by: Unable to resolve travelagency/1.0.0: missing requirement [travelagency/1.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.activemq.camel.component)(version>=5.11.0)(!(version>=6.0.0)))"]
  at org.apache.felix.resolver.Candidates.populateResource(Candidates.java:285)
  at org.apache.felix.resolver.Candidates.populate(Candidates.java:153)
  at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:148)
  at io.fabric8.agent.DeploymentBuilder.resolve(DeploymentBuilder.java:231)
  at io.fabric8.agent.DeploymentAgent.doUpdate(DeploymentAgent.java:567)
  at io.fabric8.agent.DeploymentAgent$2.run(DeploymentAgent.java:293)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
```

Searching for this issue on the internet I found this blog post [1] (http://www.rubix.nl/blogs/fuse-fabric-mq-provision-exception). According to that post the author says you have to add and `Export-Package` directive in the `maven-bundle-plugin` configuration like this:

```
<Export-Package>org.apache.activemq.camel.component</Export-Package>
```

Actually after adding that directive in the pom.xml of all projects the error disappeared.
```
       <plugin>
         <groupId>org.apache.felix</groupId>
         <artifactId>maven-bundle-plugin</artifactId>
         <version>2.3.7</version>
         <extensions>true</extensions>
         <configuration>
           <instructions>
             <Bundle-SymbolicName>travelagency</Bundle-SymbolicName>
             <Private-Package>org.blogdemo.travelagency.*</Private-Package>
             <Import-Package>*</Import-Package>
             <Export-Package>org.apache.activemq.camel.component</Export-Package>
           </instructions>
         </configuration>
       </plugin>
```

[1] http://www.rubix.nl/blogs/fuse-fabric-mq-provision-exception

**Comment by weimeilin79** [comment]
fixed the version. check again

**Comment by eschabell** [comment]
All updated in fuse 6.2 now, please retest and reopen if needed.
